<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2fcXZGt' shared service.

return $this->privates['.service_locator.2fcXZGt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CartController::index' => ['privates', '.service_locator.PeS.Fgc', 'get_ServiceLocator_PeS_FgcService.php', true],
    'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true],
    'App\\Controller\\CategoryController::show' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CheckoutController::index' => ['privates', '.service_locator.PeS.Fgc', 'get_ServiceLocator_PeS_FgcService.php', true],
    'App\\Controller\\ProductController::add' => ['privates', '.service_locator.2G0rgMK', 'get_ServiceLocator_2G0rgMKService.php', true],
    'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController::index' => ['privates', '.service_locator.PeS.Fgc', 'get_ServiceLocator_PeS_FgcService.php', true],
    'App\\Controller\\ProductController::show' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\CartController:index' => ['privates', '.service_locator.PeS.Fgc', 'get_ServiceLocator_PeS_FgcService.php', true],
    'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.a.laFVK', 'get_ServiceLocator_A_LaFVKService.php', true],
    'App\\Controller\\CategoryController:show' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CheckoutController:index' => ['privates', '.service_locator.PeS.Fgc', 'get_ServiceLocator_PeS_FgcService.php', true],
    'App\\Controller\\ProductController:add' => ['privates', '.service_locator.2G0rgMK', 'get_ServiceLocator_2G0rgMKService.php', true],
    'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
    'App\\Controller\\ProductController:index' => ['privates', '.service_locator.PeS.Fgc', 'get_ServiceLocator_PeS_FgcService.php', true],
    'App\\Controller\\ProductController:show' => ['privates', '.service_locator.ZzSB_Y3', 'get_ServiceLocator_ZzSBY3Service.php', true],
], [
    'App\\Controller\\CartController::index' => '?',
    'App\\Controller\\CategoryController::delete' => '?',
    'App\\Controller\\CategoryController::edit' => '?',
    'App\\Controller\\CategoryController::index' => '?',
    'App\\Controller\\CategoryController::show' => '?',
    'App\\Controller\\CheckoutController::index' => '?',
    'App\\Controller\\ProductController::add' => '?',
    'App\\Controller\\ProductController::delete' => '?',
    'App\\Controller\\ProductController::edit' => '?',
    'App\\Controller\\ProductController::index' => '?',
    'App\\Controller\\ProductController::show' => '?',
    'App\\Controller\\CartController:index' => '?',
    'App\\Controller\\CategoryController:delete' => '?',
    'App\\Controller\\CategoryController:edit' => '?',
    'App\\Controller\\CategoryController:index' => '?',
    'App\\Controller\\CategoryController:show' => '?',
    'App\\Controller\\CheckoutController:index' => '?',
    'App\\Controller\\ProductController:add' => '?',
    'App\\Controller\\ProductController:delete' => '?',
    'App\\Controller\\ProductController:edit' => '?',
    'App\\Controller\\ProductController:index' => '?',
    'App\\Controller\\ProductController:show' => '?',
]);
