<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIelq7ob\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIelq7ob/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIelq7ob.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIelq7ob\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIelq7ob\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ielq7ob',
    'container.build_id' => '9c2807a4',
    'container.build_time' => 1567529630,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIelq7ob');
