<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSDd5juh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSDd5juh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSDd5juh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSDd5juh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSDd5juh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SDd5juh',
    'container.build_id' => 'a815e3fc',
    'container.build_time' => 1568142384,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSDd5juh');
